### ISSUE TITLE
회원등록 시 모든 항목 빈칸으로 등록해도 DB에 저장되는 현상있습니다

### ISSUE THREAD

**Issue by mohag123** [KangWCB/comgram#1]
**프론트엔드 쪽에서 모든 항목을 필수로 입력해야만 데이터가 전송되게끔 수정**했는데
백엔드 쪽에서도 공백 데이터 저장되는 현상 자체를 막아두는게 좋을 것 같습니다

근데 원래 테이블에 그런 식으로 저장될 수도 있는게 맞으면
프론트 쪽에서 이런 예외들을 신경써서 처리하는 걸로 하구요

**Comment by shinb-bong** [comment]
에러처리 하면서 막을려고 기능구현 => 에러처리 하면서 막음
DB , 서버 , 프론트 모두 막을예정
